# Generated by Django 6.0.3 on 2026-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
