# Generated by Django 6.0.3 on 2026-03-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_alter_company_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="application",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.application",
            ),
        ),
    ]
