# Generated by Django 6.0.3 on 2026-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="experience_years",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Tajribasiz"),
                    (1, "1 yil"),
                    (2, "2 yil"),
                    (3, "3 yil"),
                    (5, "5 yil"),
                    (10, "10+ yil"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "To'liq stavka"),
                    ("part_time", "Yarim stavka"),
                    ("contract", "Kontrakt"),
                    ("freelance", "Frilans"),
                    ("internship", "Stajirovka"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Toshkent", "Toshkent"),
                    ("Samarqand", "Samarqand"),
                    ("Buxoro", "Buxoro"),
                    ("Andijon", "Andijon"),
                    ("Farg'ona", "Farg'ona"),
                    ("Namangan", "Namangan"),
                    ("Qashqadaryo", "Qashqadaryo"),
                    ("Surxondaryo", "Surxondaryo"),
                    ("Jizzax", "Jizzax"),
                    ("Sirdaryo", "Sirdaryo"),
                    ("Navoiy", "Navoiy"),
                    ("Xorazm", "Xorazm"),
                    ("Qoraqalpog'iston", "Qoraqalpog'iston"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_max",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_min",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
