# Generated by Django 6.0.3 on 2026-05-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_vacancy_experience_years_vacancy_job_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="region",
        ),
    ]
