# Generated by Django 6.0.3 on 2026-05-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_remove_vacancy_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_range",
        ),
    ]
