# Generated by Django 6.0.3 on 2026-03-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_certificate_student_remove_education_student_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="file_url",
            new_name="link",
        ),
        migrations.AddField(
            model_name="certificate",
            name="files",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
