from .registration import RegistrationForm
from .student_profile import StudentProfileForm
from .add_skills import SkillForm
from .education import EducationForm
from .experience import ExperienceForm
from .login import LoginForm
from .password_change import CustomPasswordChangeForm
from .password_set_confirm import CustomSetPasswordForm
from .language import LanguageForm
from .portfolio import PortfolioForm
from .certificate import CertificateForm